services:
  productos:
    image: dillescas01/api-productos
    ports:
      - "8000:8000"
    networks:
      - mi_red

  pedidos:
    image: dillescas01/api-pedidos
    ports:
      - "8001:8001"
    networks:
      - mi_red
    depends_on:
      - productos

  usuarios:
    image: dillescas01/api-usuarios
    ports:
      - "5000:5000"
    networks:
      - mi_red
    environment:
      - MONGO_URI=mongodb://98.82.74.138:27017/usuarios

  orquestador:
    image: dillescas01/orquestador
    ports:
      - "8080:8080"
    networks:
      - mi_red
    depends_on:
      - productos
      - pedidos

networks:
  mi_red:
    driver: bridge